Ensure "bandit" security scans do not fail workflow runs

diff --git a/.github/workflows/python-test.yml b/.github/workflows/python-test.yml
--- a/.github/workflows/python-test.yml
+++ b/.github/workflows/python-test.yml
@@ -33,7 +33,7 @@ jobs:
         path: htmlcov/
     
     - name: Run Bandit Vulnerability Scan
-      run: bandit -r src/ -o bandit-report.txt
+      run: bandit -r src/ -o bandit-report.txt || true # report vulns for now, don't fail workflow
 
     - name: Upload Bandit Report
       uses: actions/upload-artifact@v2
